name: mituna
description: Mituna est une application de quiz passionnante qui met à l'épreuve vos connaissances sur la République Démocratique du Congo (RDC) ainsi que sur diverses questions liées au monde.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.3+25

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.17
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  google_sign_in: ^6.3.0
  adaptive_dialog: ^2.4.0
  firebase_messaging: ^15.2.4
  upgrader: ^11.3.1
  hooks_riverpod: ^2.6.1
  cloud_firestore: ^5.6.5
  simple_animations: ^5.1.0
  lottie: ^3.3.1
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.31
  path_provider: ^2.1.5
  path: ^1.9.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.2
  uuid: ^4.5.1
  vibration: ^3.1.3
  sound_library: ^1.0.0
  tuple: ^2.0.2
  cached_network_image: ^3.4.1
  intl: any
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  firebase_storage: ^12.4.4
  flutter_form_builder: ^10.0.1
  package_info_plus: ^8.3.0
  rate_my_app: ^2.3.1
  faker: ^2.2.0
  riverpod_annotation: ^2.6.1
  string_extensions: ^0.7.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  mockito: ^5.4.5
  firebase_auth_mocks: ^0.14.1
  fake_cloud_firestore: ^3.1.0
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/icons/
    - assets/lottiefiles/
    - assets/lottiefiles/happy/
    - assets/lottiefiles/sad/
    - assets/images/
    - assets/images/categories/
    - assets/sounds/
    - assets/data/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Light.ttf
          weight: 400
        - asset: fonts/Lato-Thin.ttf
          weight: 200

flutter_native_splash:
  color: "#1d87ff"
  image: "assets/images/mituna.png"
  branding_mode: center

  android_12:
    color: "#1d87ff"
    image: "assets/images/mituna.png"
    branding_mode: center

  fullscreen: true

flutter_launcher_icons:
  android: "mituna"
  ios: true
  image_path: "assets/images/mituna_rounded.png"
  image_path_ios: "assets/images/appstore.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#1d87ff"
  adaptive_icon_foreground: "assets/images/mituna_rounded.png"