name: mituna
description: Mituna est une application de quiz passionnante qui met à l'épreuve vos connaissances sur la République Démocratique du Congo (RDC) ainsi que sur diverses questions liées au monde.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+19

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutter_hooks: ^0.20.0
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_sign_in: ^6.1.4
  adaptive_dialog: ^1.9.0
  firebase_messaging: ^14.6.5
  upgrader: ^8.1.0
  hooks_riverpod: ^2.4.9
  cloud_firestore: ^4.8.4
  simple_animations: ^5.0.2
  lottie: ^2.6.0
  drift: ^2.11.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.0
  path: ^1.8.3
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  vibration: ^1.8.1
  soundpool: ^2.3.0
  cloud_functions: ^4.4.0
  tuple: ^2.0.2
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  image_picker: ^1.0.2
  flutter_image_compress: ^2.0.4
  firebase_storage: ^11.2.6
  flutter_form_builder: ^9.1.0
  gsheets: ^0.5.0
  package_info_plus: ^4.1.0
  confetti: ^0.7.0
  rate_my_app: ^2.0.0
  faker: ^2.1.0
  riverpod_annotation: ^2.3.3
  yaml: ^3.1.2
  string_extensions: ^0.6.13
  envied: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  drift_dev: ^2.11.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  mockito: ^5.4.2
  firebase_auth_mocks: ^0.12.0
  fake_cloud_firestore: ^2.4.1+1
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/icons/
    - assets/lottiefiles/
    - assets/lottiefiles/happy/
    - assets/lottiefiles/sad/
    - assets/images/
    - assets/images/categories/
    - assets/sounds/
    - assets/data/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Light.ttf
          weight: 400
        - asset: fonts/Lato-Thin.ttf
          weight: 200

flutter_native_splash:
  color: "#1d87ff"
  image: "assets/images/mituna.png"
  branding_mode: center

  android_12:
    color: "#1d87ff"
    image: "assets/images/mituna.png"
    branding_mode: center

  fullscreen: true

flutter_launcher_icons:
  android: "mituna"
  ios: true
  image_path: "assets/images/mituna_rounded.png"
  image_path_ios: "assets/images/appstore.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#1d87ff"
  adaptive_icon_foreground: "assets/images/mituna_rounded.png"