import 'package:firebase_auth/firebase_auth.dart';

extension FirebaseAuthMessageFr on FirebaseException {
  String? get messageFr {
    return _errorMessages[code] ?? message;
  }
}

const _errorMessages = {
  'app-deleted': 'Cette instance Firebase n\'est plus disponible.',
  'app-not-authorized': 'Cette application n\'est pas autorisée à utiliser Firebase Authentication.',
  'argument-error': 'Vérifiez les paramètres fournis à la méthode d\'authentification.',
  'invalid-api-key': 'La clé API fournie est invalide ou mal configurée.',
  'invalid-user-token': 'Le jeton utilisateur fourni est invalide.',
  'network-request-failed': 'Une erreur réseau est survenue.',
  'operation-not-allowed': 'Opération non permise.',
  'requires-recent-login': 'L\'utilisateur doit se reconnecter pour effectuer cette opération.',
  'too-many-requests': 'Trop de requêtes en peu de temps. Veuillez réessayer plus tard.',
  'unauthorized-domain': 'Le domaine de l\'application n\'est pas autorisé.',
  'user-disabled': 'Cet utilisateur est désactivé.',
  'user-token-expired': 'Le jeton utilisateur a expiré.',
  'web-storage-unsupported': 'Le navigateur ne supporte pas le stockage web.',
  'wrong-password': 'Le mot de passe est invalide.',
  'invalid-email': 'L\'email est invalide.',
  'user-not-found': 'Aucun utilisateur avec cet email.',
  'email-already-in-use': 'Cet email est déjà utilisé.',
  'weak-password': 'Le mot de passe doit contenir 6 caractères minimum.',
  'account-exists-with-different-credential': 'Un compte existe déjà avec les mêmes identifiants.',
  'auth-domain-config-required': 'La configuration de domaine d\'authentification est requise.',
  'cancelled-popup-request': 'Requête popup annulée par l\'utilisateur.',
  'operation-not-supported-in-this-environment': 'Cette opération n\'est pas supportée dans cet environnement.',
  'popup-blocked': 'La popup a été bloquée par le navigateur.',
  'popup-closed-by-user': 'La popup a été fermée par l\'utilisateur.',
  'credential-already-in-use': 'L\'identifiant est déjà utilisé.',
  'email-change-needs-verification': 'Le changement d\'email nécessite une vérification.',
  'expired-action-code': 'Le code d\'action a expiré.',
  'invalid-action-code': 'Le code d\'action est invalide.',
  'invalid-verification-code': 'Le code de vérification est invalide.',
  'invalid-verification-id': 'L\'ID de vérification est invalide.',
  'missing-android-pkg-name': 'Le nom du package Android est requis.',
  'missing-app-credential': 'Les identifiants de l\'application sont requis.',
  'missing-verification-code': 'Le code de vérification est requis.',
  'missing-continue-uri': 'L\'URL de continuation est requise.',
  'missing-iframe-start': 'Le démarrage Iframe est requis.',
  'missing-ios-bundle-id': 'L\'ID du bundle iOS est requis.',
  'missing-or-invalid-nonce': 'Le nonce est invalide ou manquant.',
  'missing-multi-factor-info': 'Les détails du second facteur sont requis.',
  'missing-multi-factor-session': 'La session multi-facteur est requise.',
  'multi-factor-auth-required': 'L\'authentification multi-facteur est requise.',
  'maximum-user-count-exceeded': 'Le nombre maximum d\'utilisateurs est dépassé.',
  'session-cookie-revoked': 'Le cookie de session a été révoqué.',
  'tenant-id-mismatch': 'Le tenant ID ne correspond pas.',
  'timeout': 'Délai d\'opération dépassé.',
  'dynamic-link-not-activated': 'Le lien dynamique n\'est pas activé.',
  'invalid-persistence-type': 'Type de persistance invalide.',
  'unsupported-persistence-type': 'Type de persistance non supporté.',
  'invalid-user-import': 'Import d\'utilisateur invalide.',
  'unsupported-tenant-operation': 'Opération tenant non supportée.',
};
